import type { BrainFileNode, ProjectSummary } from '@shared/brain'

/**
 * Goal Mode (spec §29-§32). A goal breaks into tasks; each task carries a
 * *checkable signal* so Lumixa computes done-ness from the real project state
 * (files, tests) — never from an AI claiming "80% complete" (§32). The breakdown
 * can be generated by Claude Code, but progress is always measured here.
 *
 * Pure + unit-tested; the store handles persistence + Claude orchestration.
 */

export type Complexity = 'low' | 'medium' | 'high'
export type CheckType = 'file' | 'keyword' | 'tests' | 'manual'

export interface TaskCheck {
  type: CheckType
  /** Path glob (file), search term (keyword); unused for tests/manual. */
  value?: string
}

export interface GoalTask {
  id: string
  title: string
  hint?: string
  complexity?: Complexity
  check: TaskCheck
  /** User-set completion, only consulted for `manual` checks. */
  manualDone?: boolean
}

export interface Goal {
  text: string
  tasks: GoalTask[]
  createdAt: number
}

export interface EvalContext {
  files: { rel: string; exports: string[] }[]
  /** Result of the last test run, or null if unknown. */
  testsPass: boolean | null
}

function globToRegExp(glob: string): RegExp {
  const escaped = glob.replace(/[.+^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*')
  return new RegExp(escaped, 'i')
}

/** Deterministically decide whether a task is done from real project state. */
export function evaluateTask(task: GoalTask, ctx: EvalContext): boolean {
  switch (task.check.type) {
    case 'manual':
      return task.manualDone === true
    case 'tests':
      return ctx.testsPass === true
    case 'file': {
      const v = task.check.value
      if (!v) return false
      if (v.includes('*')) {
        const re = globToRegExp(v)
        return ctx.files.some((f) => re.test(f.rel))
      }
      const lower = v.toLowerCase()
      return ctx.files.some((f) => f.rel.toLowerCase().includes(lower))
    }
    case 'keyword': {
      const v = task.check.value?.toLowerCase()
      if (!v) return false
      return ctx.files.some(
        (f) => f.rel.toLowerCase().includes(v) || f.exports.some((e) => e.toLowerCase().includes(v))
      )
    }
    default:
      return false
  }
}

export interface Progress {
  done: number
  total: number
  percent: number
}

export function computeProgress(tasks: GoalTask[], ctx: EvalContext): Progress {
  const done = tasks.filter((t) => evaluateTask(t, ctx)).length
  const total = tasks.length
  return { done, total, percent: total === 0 ? 0 : Math.round((done / total) * 100) }
}

/** The first not-yet-done task — the recommended next action (§31). */
export function nextAction(tasks: GoalTask[], ctx: EvalContext): GoalTask | null {
  return tasks.find((t) => !evaluateTask(t, ctx)) ?? null
}

// ---------------------------------------------------------------------------
// Claude Code breakdown (generate + parse)
// ---------------------------------------------------------------------------

export function buildBreakdownPrompt(goal: string, summary: ProjectSummary | null): string {
  const stack = summary
    ? [summary.framework, summary.language, summary.build, summary.testing].filter(Boolean).join(' · ')
    : 'unknown stack'
  return (
    `Break this development goal into 6-12 concrete, ordered tasks for THIS project ` +
    `(${stack}). Reply with ONLY a JSON array inside a \`\`\`json code block — no prose.\n\n` +
    `Each task: {"title": string, "hint": string, "complexity": "low"|"medium"|"high", ` +
    `"check": {"type": "file"|"keyword"|"tests"|"manual", "value": string}}.\n` +
    `The check tells Lumixa how to detect completion automatically:\n` +
    `- "file": value is a path or glob that will exist when done (e.g. "src/cart/*").\n` +
    `- "keyword": value is a filename/symbol substring that appears when done.\n` +
    `- "tests": completion is "the test suite passes".\n` +
    `- "manual": no automatic signal (user marks it done).\n\n` +
    `Goal: ${goal}`
  )
}

/** Extract a task array from Claude's response; tolerant of surrounding text. */
export function parseTasksFromResponse(text: string): GoalTask[] {
  const raw = extractJsonArray(text)
  if (!raw) return []
  let arr: unknown
  try {
    arr = JSON.parse(raw)
  } catch {
    return []
  }
  if (!Array.isArray(arr)) return []
  const tasks: GoalTask[] = []
  const types: CheckType[] = ['file', 'keyword', 'tests', 'manual']
  arr.forEach((item, i) => {
    const o = item as Record<string, unknown>
    const title = typeof o.title === 'string' ? o.title.trim() : ''
    if (!title) return
    const checkO = (o.check ?? {}) as Record<string, unknown>
    const type = types.includes(checkO.type as CheckType) ? (checkO.type as CheckType) : 'manual'
    const complexity = (['low', 'medium', 'high'] as const).includes(o.complexity as Complexity)
      ? (o.complexity as Complexity)
      : undefined
    tasks.push({
      id: `t${i}_${Date.now().toString(36)}`,
      title: title.slice(0, 160),
      hint: typeof o.hint === 'string' ? o.hint.slice(0, 300) : undefined,
      complexity,
      check: { type, value: typeof checkO.value === 'string' ? checkO.value : undefined }
    })
  })
  return tasks
}

function extractJsonArray(text: string): string | null {
  const fence = text.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (fence && fence[1].includes('[')) return fence[1].trim()
  const start = text.indexOf('[')
  const end = text.lastIndexOf(']')
  if (start >= 0 && end > start) return text.slice(start, end + 1)
  return null
}

export function buildTaskPrompt(goalText: string, task: GoalTask): string {
  return (
    `Work on this task for the goal "${goalText}":\n\n` +
    `## ${task.title}\n${task.hint ?? ''}\n\n` +
    `Implement it in this project following the existing conventions and file structure. ` +
    `Keep the change focused on this task.`
  )
}
